name: backend
description: A simple backend using Dart and Shelf
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  postgres: ^2.3.2
  uuid: ^3.0.4